export interface Quote {
  text: string;
  author: string;
}

export const MOTIVATIONAL_QUOTES: Quote[] = [
  { text: "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos.", author: "Michael Jordan" },
  { text: "No tiene sentido contratar a personas inteligentes y después decirles lo que tienen que hacer. Nosotros contratamos a personas inteligentes para que nos digan qué tenemos que hacer.", author: "Steve Jobs" },
  { text: "El único modo de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
  { text: "Un líder es alguien que conoce el camino, recorre el camino y muestra el camino.", author: "John C. Maxwell" },
  { text: "La innovación distingue a los líderes de los seguidores.", author: "Steve Jobs" },
  { text: "Para construir una empresa excepcional, necesitas talento excepcional.", author: "Anónimo" },
  { text: "Si quieres ir rápido, ve solo. Si quieres llegar lejos, ve acompañado.", author: "Proverbio Africano" },
  { text: "Las grandes cosas en los negocios nunca son hechas por una sola persona. Son hechas por un equipo de personas.", author: "Steve Jobs" },
  { text: "Ninguno de nosotros es tan inteligente como todos nosotros.", author: "Ken Blanchard" },
  { text: "El recurso más valioso que tiene cualquier empresa son sus personas.", author: "Anónimo" },
  { text: "Juntarse es un comienzo. Mantenerse juntos es progreso. Trabajar juntos es el éxito.", author: "Henry Ford" },
  { text: "La forma en que tratas a tus empleados es la forma en que ellos tratarán a tus clientes.", author: "Richard Branson" },
  { text: "El liderazgo no se trata de estar a cargo. Se trata de cuidar a las personas a tu cargo.", author: "Simon Sinek" },
  { text: "Cuando las personas sienten que su trabajo tiene propósito, la magia ocurre.", author: "Anónimo" },
  { text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito.", author: "Albert Schweitzer" },
  { text: "La mejor manera de predecir el futuro es creándolo.", author: "Peter Drucker" },
  { text: "Contrata carácter. Entrena la habilidad.", author: "Peter Schutz" },
  { text: "El éxito de tu negocio se mide por el nivel de talento que logras retener.", author: "Anónimo" },
  { text: "Una máquina puede hacer el trabajo de cincuenta hombres ordinarios. Ninguna máquina puede hacer el trabajo de un hombre extraordinario.", author: "Elbert Hubbard" },
  { text: "El secreto del cambio es enfocar toda tu energía, no en luchar contra lo viejo, sino en construir lo nuevo.", author: "Sócrates" },
  { text: "Trata siempre a tus empleados exactamente como quieres que ellos traten a tus mejores clientes.", author: "Stephen R. Covey" },
  { text: "Lo que haces habla tan fuerte que no puedo escuchar lo que dices.", author: "Ralph Waldo Emerson" },
  { text: "Un buen líder lleva a las personas a donde quieren ir. Un gran líder las lleva a donde no necesariamente quieren ir, pero deben estar.", author: "Rosalynn Carter" },
  { text: "Si crees que contratar profesionales es caro, prueba contratando novatos.", author: "Anónimo" },
  { text: "La cultura se come a la estrategia en el desayuno.", author: "Peter Drucker" },
  { text: "El capital más importante de tu empresa es el humano.", author: "Anónimo" },
  { text: "La excelencia no es un acto, es un hábito.", author: "Aristóteles" },
  { text: "No intentes convertirte en un hombre de éxito, sino en un hombre de valor.", author: "Albert Einstein" },
  { text: "No puedes enseñar a los empleados a sonreír. Tienen que sonreír antes de que los contrates.", author: "Arte Nathan" },
  { text: "Los líderes que ofrecen sangre, sudor y lágrimas, siempre obtienen más de sus seguidores que aquellos que ofrecen seguridad y diversión.", author: "George Orwell" },
  { text: "Invierte en tu gente, o no inviertas en absoluto.", author: "Anónimo" },
  { text: "Toma 20 años construir una reputación y cinco minutos arruinarla.", author: "Warren Buffett" },
  { text: "La motivación nos impulsa a comenzar y el hábito nos permite continuar.", author: "Jim Ryun" },
  { text: "Las fortalezas están en nuestras diferencias, no en nuestras similitudes.", author: "Stephen Covey" },
  { text: "Los empleados comprometidos construyen marcas fuertes.", author: "Anónimo" },
  { text: "Encuentra personas extraordinarias y dales alas.", author: "Anónimo" },
  { text: "El talento verdadero se revela en la adversidad.", author: "Anónimo" },
  { text: "No encontramos grandes empresas, encontramos grandes equipos.", author: "Anónimo" },
  { text: "Para ser el mejor, debes ser capaz de manejar lo peor.", author: "Wilson Kanadi" },
  { text: "Una organización está compuesta por la suma de las historias de su gente.", author: "Anónimo" },
  { text: "Cuidar de tu equipo no es un gasto, es la mejor inversión.", author: "Anónimo" },
  { text: "La confianza es el pegamento de la vida. Es el ingrediente principal en la comunicación efectiva.", author: "Stephen Covey" },
  { text: "No te limites a construir un negocio. Construye a las personas que construirán el negocio.", author: "Anónimo" },
  { text: "El talento te abre la puerta, el carácter te mantiene dentro.", author: "Anónimo" },
  { text: "El verdadero liderazgo es empoderar a los demás para que logren más de lo creían posible.", author: "Anónimo" },
  { text: "Cada contratación exitosa eleva el estándar de toda la empresa.", author: "Anónimo" },
  { text: "Formar un equipo es solo el principio; mantenerlo unido es el éxito.", author: "Henry Ford" },
  { text: "Acepta el desafío, porque detrás de cada problema hay una oportunidad de crecimiento.", author: "Anónimo" },
  { text: "El aprendizaje continuo es el requisito mínimo para el éxito en cualquier campo.", author: "Brian Tracy" },
  { text: "El valor de tu empresa crece cuando el valor de tu gente crece.", author: "Anónimo" },
  { text: "La pasión por lo que haces te llevará más lejos que cualquier habilidad técnica.", author: "Anónimo" },
  { text: "Nunca dudes que un pequeño grupo de ciudadanos pensantes y comprometidos puede cambiar el mundo.", author: "Margaret Mead" },
  { text: "El mejor indicador del éxito de un empleado es su actitud.", author: "Anónimo" },
  { text: "Contratamos por actitud y entrenamos para la habilidad.", author: "Tom Peters" },
  { text: "Tu red es tu patrimonio neto.", author: "Porter Gale" },
  { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
  { text: "Un equipo cohesionado es un escudo contra la adversidad.", author: "Anónimo" },
  { text: "La verdadera medida de liderazgo es la influencia, nada más y nada menos.", author: "John C. Maxwell" },
  { text: "El desarrollo del talento no es un evento, es un proceso continuo.", author: "Anónimo" },
  { text: "A veces la persona más pequeña puede cambiar el curso del futuro.", author: "J.R.R. Tolkien" },
  { text: "Enfócate en la solución, no en el problema.", author: "Anónimo" },
  { text: "Crea un entorno donde el talento no quiera irse.", author: "Anónimo" },
  { text: "La calidad de un líder se refleja en los estándares que establece para sí mismo.", author: "Ray Kroc" },
  { text: "Si el plan no funciona, cambia el plan, pero nunca cambies la meta.", author: "Anónimo" },
  { text: "Las personas felices producen resultados extraordinarios.", author: "Anónimo" },
  { text: "Da siempre lo mejor de ti. Lo que plantes ahora, lo cosecharás más tarde.", author: "Og Mandino" },
  { text: "Cuando las personas están financieramente seguras y apoyadas emocionalmente, son libres de crear.", author: "Anónimo" },
  { text: "No busques errores, busca soluciones.", author: "Henry Ford" },
  { text: "La integridad es hacer lo correcto aunque nadie te esté mirando.", author: "C.S. Lewis" },
  { text: "Escucha a tus empleados. Ellos saben cómo hacer que el barco vaya más rápido.", author: "Anónimo" },
  { text: "La gestión de personas es el pilar de la rentabilidad.", author: "Anónimo" },
  { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier" },
  { text: "El trabajo duro vence al talento cuando el talento no trabaja duro.", author: "Tim Notke" },
  { text: "Inspirar a tu equipo es tu trabajo número uno.", author: "Anónimo" },
  { text: "Una cultura sólida atrae talentos sólidos.", author: "Anónimo" },
  { text: "Nunca dejes de aprender, porque la vida nunca deja de enseñar.", author: "Anónimo" },
  { text: "Empoderamiento significa confiar en que tu equipo tomará las decisiones correctas.", author: "Anónimo" },
  { text: "La comunicación es la clave del trabajo en equipo efectivo.", author: "Anónimo" },
  { text: "No evalúes el éxito por los logros de hoy, sino por el talento que estás desarrollando para el mañana.", author: "Anónimo" },
  { text: "Un error es solo otra oportunidad para hacer las cosas mejor la próxima vez.", author: "Anónimo" },
  { text: "La adaptabilidad es la inteligencia del siglo XXI.", author: "Anónimo" },
  { text: "Si contratas a personas que creen en lo mismo que tú crees, trabajarán para ti con sangre, sudor y lágrimas.", author: "Simon Sinek" },
  { text: "No es lo que logras, es lo que superas. Eso es lo que define tu carrera.", author: "Carlton Fisk" },
  { text: "Las palabras inspiran, pero las acciones transforman.", author: "Anónimo" },
  { text: "El reclutamiento trata sobre encontrar a las personas adecuadas, pero la retención trata sobre ser la empresa adecuada.", author: "Anónimo" },
  { text: "Haz que tu lugar de trabajo sea tan inspirador como tus productos.", author: "Anónimo" },
  { text: "Un equipo sin confianza es simplemente un grupo de individuos.", author: "Anónimo" },
  { text: "No importa cuán brillante sea tu mente o estrategia, si juegas solo, siempre perderás frente a un equipo.", author: "Reid Hoffman" },
  { text: "Rodéate de personas más inteligentes que tú y apártate de su camino.", author: "Anónimo" },
  { text: "El futuro pertenece a aquellos que creen en la belleza de sus sueños.", author: "Eleanor Roosevelt" },
  { text: "Un buen empleado es difícil de encontrar, difícil de mantener e imposible de olvidar.", author: "Anónimo" },
  { text: "No hay atajos hacia ningún lugar que valga la pena.", author: "Beverly Sills" },
  { text: "La resiliencia de un equipo se forma en los desafíos, no en la comodidad.", author: "Anónimo" },
  { text: "Construye líderes, no seguidores.", author: "Anónimo" },
  { text: "Un equipo unido puede mover montañas.", author: "Anónimo" },
  { text: "Sé el tipo de líder que la gente seguiría voluntariamente, incluso si no tuvieras título ni posición.", author: "Brian Tracy" },
  { text: "Tu carrera es tu negocio. Es hora de gestionarla como un CEO.", author: "Andy Grove" },
  { text: "El respeto no se exige, se gana.", author: "Anónimo" },
  { text: "Un talento descubierto a tiempo cambia la historia de una empresa.", author: "Anónimo" },
  { text: "La gratitud en el equipo es el combustible de la innovación.", author: "Anónimo" }
];
