"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _plantilla_page from './plantilla-page.bones.json'
import _candidatos_page from './candidatos-page.bones.json'
import _bajas_page from './bajas-page.bones.json'
import _reportes_page from './reportes-page.bones.json'
import _analisis_page from './analisis-page.bones.json'
import _configuracion_indicadores from './configuracion-indicadores.bones.json'
import _configuracion_rutas from './configuracion-rutas.bones.json'
import _configuracion_tabulador from './configuracion-tabulador.bones.json'
import _configuracion_speech from './configuracion-speech.bones.json'
import _configuracion_formatos from './configuracion-formatos.bones.json'
import _actividades_page from './actividades-page.bones.json'
import _plantilla_empleados from './plantilla-empleados.bones.json'
import _resumen_page from './resumen-page.bones.json'

configureBoneyard({"color":"var(--color-hairline)","darkColor":"var(--color-hairline)","animate":"solid","speed":"var(--duration-skeleton)","boneClass":"boneyard-skeleton__bone"})

registerBones({
  "plantilla-page": _plantilla_page,
  "candidatos-page": _candidatos_page,
  "bajas-page": _bajas_page,
  "reportes-page": _reportes_page,
  "analisis-page": _analisis_page,
  "configuracion-indicadores": _configuracion_indicadores,
  "configuracion-rutas": _configuracion_rutas,
  "configuracion-tabulador": _configuracion_tabulador,
  "configuracion-speech": _configuracion_speech,
  "configuracion-formatos": _configuracion_formatos,
  "actividades-page": _actividades_page,
  "plantilla-empleados": _plantilla_empleados,
  "resumen-page": _resumen_page,
})
