-- 1. Add colonia to empleados
ALTER TABLE public.empleados ADD COLUMN IF NOT EXISTS colonia text;

-- 2. Create rutas_snapshots table to store historical daily snapshot
CREATE TABLE IF NOT EXISTS public.rutas_snapshots (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    snapshot_data jsonb not null
);

-- Grant permissions for read/insert
GRANT SELECT, INSERT ON public.rutas_snapshots TO authenticated;

-- 3. Create RPC for bulk upload
CREATE OR REPLACE FUNCTION update_empleados_rutas(payload jsonb)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$$
DECLARE
    previous_snapshot jsonb;
BEGIN
    -- Take a snapshot of CURRENT routes before update
    SELECT jsonb_agg(
        jsonb_build_object(
            'numeroEmpleado', num_empleado,
            'nombre', nombre,
            'turno', turno,
            'nombreRuta', ruta,
            'colonia', colonia,
            'parada', parada,
            'seccion', seccion
        )
    ) INTO previous_snapshot
    FROM public.empleados
    WHERE ruta IS NOT NULL AND ruta != '';
    
    IF previous_snapshot IS NULL THEN
        previous_snapshot := '[]'::jsonb;
    END IF;

    -- Insert snapshot
    INSERT INTO public.rutas_snapshots(snapshot_data) VALUES (previous_snapshot);

    -- Keep only the latest 5 snapshots to avoid bloating the DB over time
    DELETE FROM public.rutas_snapshots
    WHERE id NOT IN (
        SELECT id FROM public.rutas_snapshots ORDER BY created_at DESC LIMIT 5
    );

    -- Limpiamos las rutas de TODOS para que solo queden los del nuevo JSON
    UPDATE public.empleados
    SET ruta = NULL, parada = NULL, colonia = NULL
    WHERE ruta IS NOT NULL;

    -- Apply new routes from JSON payload
    WITH new_routes AS (
        SELECT 
            COALESCE(value->>'numero_empleado', value->>'numero empleado', value->>'Num Empleado') AS num_emp,
            COALESCE(value->>'nombre_ruta', value->>'nombre ruta', value->>'Ruta') AS p_ruta,
            COALESCE(value->>'parada', value->>'Parada') AS p_parada,
            COALESCE(value->>'colonia', value->>'Colonia') AS p_colonia,
            COALESCE(value->>'turno', value->>'Turno') AS p_turno,
            COALESCE(value->>'seccion', value->>'Seccion') AS p_seccion
        FROM jsonb_array_elements(payload)
    )
    UPDATE public.empleados e
    SET 
        ruta = nr.p_ruta,
        parada = nr.p_parada,
        colonia = nr.p_colonia,
        turno = COALESCE(nr.p_turno, e.turno),
        seccion = COALESCE(nr.p_seccion, e.seccion)
    FROM new_routes nr
    WHERE e.num_empleado = nr.num_emp;
    
END;
$$$;

